name: SauceDemo CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  smoke-tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        playwright install --with-deps

    - name: Run Smoke Suite
      run: pytest -m smoke --alluredir=allure-results

    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre wget
        wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.29.0.tgz
        tar -zxvf allure-2.29.0.tgz
        sudo mv allure-2.29.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Generate Allure HTML Report
      run: allure generate allure-results --clean -o allure-report

    - name: Upload Allure HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: smoke-allure-html-report
        path: allure-report


  regression-tests:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        playwright install --with-deps

    - name: Run Regression Suite
      run: pytest -m regression --alluredir=allure-results

    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre wget
        wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.29.0.tgz
        tar -zxvf allure-2.29.0.tgz
        sudo mv allure-2.29.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Generate Allure HTML Report
      run: allure generate allure-results --clean -o allure-report

    - name: Upload Allure HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: regression-allure-html-report
        path: allure-report
