name: SauceDemo CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Smoke Suite
        run: pytest -m smoke --alluredir=allure-results

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre wget
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.36.0.tgz
          tar -zxvf allure-2.36.0.tgz
          sudo mv allure-2.36.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure HTML
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Smoke Allure HTML
        uses: actions/upload-artifact@v4
        with:
          name: smoke-allure-html
          path: allure-report


  regression-tests:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: smoke-tests

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Regression Suite
        run: pytest -m regression --alluredir=allure-results

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre wget
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.36.0.tgz
          tar -zxvf allure-2.36.0.tgz
          sudo mv allure-2.36.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure HTML
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Regression Allure HTML
        uses: actions/upload-artifact@v4
        with:
          name: regression-allure-html
          path: allure-report
